version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: |
            npm config set spin false
            npm install
            sudo npm install -g phantomjs-prebuilt

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
